---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codewith/public_html/
 #   - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
 #   - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
 #   - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css
 #   - /bin/cp ./public/images/*.jpg $DEPLOYPATH/public_html/images