---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codewith/public_html/
 #   - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp -r ./public/* $DEPLOYPATH
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/